version: "3"

services:
  ckan:
    image: keitaro/ckan:${CKAN_VERSION:-2.8.6}
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "${CKAN_PORT}:5000"
    env_file:
      - .env
      - .ckan-env
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - .:/srv/app/src/ckanext-s3filestore
      - ckan_data:/srv/app/data

  db:
    image: datagov/ckan-postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    image: datagov/catalog-solr:ckan_2.8
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    image: redis:alpine

volumes:
  ckan_data:
  pg_data:
  solr_data:
